### PR TITLE
Add automatic module names (#584)

### PR DESCRIPTION
**Pull request by comtel2000**
works for me, BR, Joerg

### CODE REVIEW

**Comment by kevinherron** [comment]
I think `bsd-parser` will need one as well?

**Comment by comtel2000** [comment]
you're right. Each 'jar' module requires a unique automatic name.
I missed **bsd-parser-gson** and **bsd-parser-core**

The **bsd-parser-core** should get a sub-package 'core' to be safe for JPMS.
I can rename/ or move it, but I don't know how many dependencies must be update too..
What do you think?

**Comment by kevinherron** [comment]
These packages have already started being reorganized on this branch in 0.4: https://github.com/eclipse/milo/tree/0.4-dtd-updates

**Comment by comtel2000** [comment]
with the 0.4-dtd-updates branch it will be more complex. the 'core' only contains the resource xsd file and core classes are moved to the previous main module?
The old structure (with a additional sub-package) looks better to get it run with the java module system.

**Comment by kevinherron** [comment]
In that branch all the code in `bsd-core` is generated at build time under the package `org.opcfoundation.opcua.binaryschema`.

**Comment by comtel2000** [comment]
ok, I need some time to check that. Once a module name is set, it's a pain in the a... to modify it later on.. :)

**Comment by kevinherron** [comment]
Ok. Any suggestions for how we can get this working for 0.3.7 without changing package names? Or should we wait and do the automatic module names in 0.4 instead?

I'm a little disoriented having just got back to work from a ~3 week holiday, but if I remember correctly I have a few branches off of dev/0.4 going and they're all pretty close to done, so a 0.4 release isn't too far in the future. Need to dig in this week and find out where everything stands.

**Comment by comtel2000** [comment]
I guess this will work now for 3.7. For the 4.0 branches and JPMS compatibility the module root packages should be unique but as long as it's not switched to fully support JPMS (module-classpath) it works also with the current state (automatic-module-names).

**Comment by kevinherron** [comment]
Okay, thanks for doing this 👍

**Comment by kevinherron** [comment]
If this is ready and looks good to you I'll merge it.

**Comment by comtel2000** [comment]
perfect, thx

**Pull request merged**
