### PR TITLE
[#61] Move classes from "sdk.core" in sdk-server to sdk-core

### PR DESCRIPTION
**Pull request by kevinherron**
This is needed for OSGi compatibility.

### CODE REVIEW

**Comment by ctron** [comment]
I had to change the package imports. But now it works without my workaround! :+1: 

Working with you awesome! Thanks!

**Comment by kevinherron** [comment]
Huh... why did the imports need to change? I ran `mvn clean verify` after the refactor and it all passed... maybe it doesn't run integration tests like I thought?

**Comment by ctron** [comment]
Hehe ... I just could suggest to use Eclipse .. it showed a few warnings in the IDE right away :grin: 

I am sorry .. I had to ... :wink:

**Comment by ctron** [comment]
Damn .. but it did mess up your code style ... sorry ... just drop that commit!

**Comment by ctron** [comment]
it is late Friday :wink:

**Comment by ctron** [comment]
I really really really have to apologize! It was my mistake!

Your commit was all fine and I messed it up! I reverted that now. Please to merge it as it was.

**Comment by kevinherron** [comment]
No problem 😄  

I'll merge both these outstanding PRs once I get some confirmation on the other one.

**Pull request merged**
