### PR TITLE
[#870]: Allow setting a certificate chain

### PR DESCRIPTION
**Pull request by ctron**
Before you submit a pull request please acknowledge the following:
- [X] You have signed an Eclipse Contributor Agreement and are committing using the same email address
- [ ] Your code contains any tests relevant to the problem you are solving
- [x] All new and existing tests passed
- [X] Code follows the style guidelines and Checkstyle passes

See [CONTRIBUTING](https://github.com/eclipse/milo/blob/master/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Comment by ctron** [comment]
>     * All new and existing tests passed

Dang … I was counting on GitHub actions or Travis to kick in.

**Comment by kevinherron** [comment]
There's a test job configured on Milo's ci.eclipse.org instance but as the only regular committer it's only triggered by my PRs :)

**Comment by ctron** [comment]
Could you insert a coin in the test machine? :grin: 

Meanwhile on my machine:

~~~
[INFO] Results:
[INFO] 
[INFO] Tests run: 88, Failures: 0, Errors: 0, Skipped: 0
~~~

**Comment by kevinherron** [comment]
rebuild

**Review by kevinherron — CHANGES_REQUESTED** [review]
The `OpcUaServerConfig.copy` method needs to set the old chain on the new builder.

**Comment by ctron** [comment]
Should be fixed.

**Review by kevinherron — APPROVED** [review]

**Comment by ctron** [comment]
Thanks for merging!

**Comment by JonasJurczok** [comment]
The updates only now reached me in the wild world.

There is a @deprecated annotation on the httpsCertificate setter method now, but no comment on what to do instead. Hence the question: what do do instead? :)

**Comment by ctron** [comment]
Use the `setHttpsCertificateChain` method.

**Pull request merged**
