### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by joesan**
Added README to run client examples!

### CODE REVIEW

**Comment by joesan** [comment]
I have no idea on how to get past the buerocracy... it is beurocrazy! My last commit message looks like this:

```
commit 4bdc2c7315b9559c9b04c74d344b824ab07889c0 (HEAD -> documentation, origin/documentation)
Author: Joesan <codeintheopen@gmail.com>
Date:   Tue Apr 9 21:37:04 2019 +0200

    Update

    Signed-off-by: Joesan <codeintheopen@gmail.com>
```
Note sure what else is expected!

**Comment by kevinherron** [comment]
If you squash these all into one commit that has the correct author and footer it should work.

**Comment by joesan** [comment]
Should the Author name match with the Eclipse user name?

**Comment by kevinherron** [comment]
I don't know if the name matters or just the email address.

**Comment by joesan** [comment]
Everything looks good with the Author and Footer, but still I could not make it!

**Comment by joesan** [comment]
Here is the latest commit: 

https://api.github.com/repos/eclipse/milo/commits/54b76ca1d5585c203d235110b307d036ee31690c

Do you see anything wrong?

**Comment by kevinherron** [comment]
The 2nd commit of the 6 doesn't have a signed-off-by in it. Again, squash these into 1 commit and it will be easier.

**Comment by joesan** [comment]
I probably need some help! Not sure when even after a squash, it would not fix the problem!

**Pull request closed without merging**
