### PR TITLE
Added hello world example.

### PR DESCRIPTION
**Pull request by hekonsek**
Hi,

I'd like to add some usage examples to Milo. Currently figuring out how to create basic application with Milo requires digging into test code and removing code you don't need.

I have created a simple Hello World example which demonstrates how to use client and custom namespace implementation in order to read/write node value. That should be a good starter for Milo newbies.

BTW I'd like to add more examples and also work on Milo's documentation.

Cheers!

### CODE REVIEW

**Comment by kevinherron** [comment]
That would be great. For examples, you could get pretty far if you brought this project back from the dead and updated it to use Milo: https://github.com/digitalpetri/opc-ua-sdk-examples

I was hoping to use the Wiki as a central location to collect documentation.

**Comment by kevinherron** [comment]
On second thought, that project may not be as useful as I thought. It uses something called `CttNamespace` as a source of nodes to program the client examples against and that no longer exists. We may have to come up with a new example namespace that has a few nodes in it.

**Comment by hekonsek** [comment]
I would propose to:
a) add my example, as it is IMHO something many people discovering the project would be interested in i.e. minimal example of client, server and namespace for read/write purposes
b) analyze opc-ua-sdk-examples and reuse what we can
c) extract more examples from existing unit tests
d) work on the documentation in parallel (GitHub wiki should do the job)

What do you think, Kevin?

**Comment by kevinherron** [comment]
Sounds okay to me. When you're ready for me to merge your examples could you please squash everything into a single commit (if you're planning to add more first) and then make sure your commit message has the "Signed-off-by: Your Name youremail@youreemail.com" footer required by the Eclipse Foundation?

**Comment by ctron** [comment]
And don't forget that when it is more than 1.000 lines of code, you will need a full CQ!

**Comment by kevinherron** [comment]
Try to keep the initial commit under 1000 lines then ;)

**Comment by hekonsek** [comment]
I will sign off this commit. Then would I propose to merge what we already have. I will create more pull requests for the next examples as I work on those. Let's focus on merging and documenting this one for the beginning.

**Comment by hekonsek** [comment]
I screwed something when I tried to sign-off my past commit. I created new cleaned pull request with proper changes - #33 . Can we got it merged?

**Pull request closed without merging**
