### PR TITLE
Add EUInformation from Unece CeFact #150

### PR DESCRIPTION
**Pull request by lln-ijinus**
Auto generated file from https://opcfoundation.org/UA/EngineeringUnits/UNECE/UNECE_to_OPCUA.csv with some utilities functions.

### CODE REVIEW

**Comment by kevinherron** [comment]
You'll need to make sure you have a CLA on file with Eclipse and sign your commit before this can be merged. See [CONTRIBUTING](https://github.com/eclipse/milo/blob/master/CONTRIBUTING.md) for more details.

**Comment by lln-ijinus** [comment]
I tried to sign the commit but it seems that it is not working. Any tips ?
Thanks

**Comment by kevinherron** [comment]
It needs the "Signed-off-by: Joe Somebody <somebody@someplace.net>" at the end of the commit message, with whatever the name and email that you registered with Eclipse and signed the CLA.

At this point you might also want to rebase and squash this all back into a single commit, and make sure that commit has the signed-off-by on it.

**Comment by kevinherron** [comment]
Almost there... validation fails because:
```
The following users do not have valid ECAs. Please see this page for details, or to sign a ECA.

    llauden@laposte.net
```

**Comment by lln-ijinus** [comment]
That's my personnal address, I can't find where it is referenced in the project ?
I just made an ECA for this address too...

**Comment by kevinherron** [comment]
You're using your personal address in the author field of your commits.

**Comment by kevinherron** [comment]
Thanks for your contribution. First one is always a little bumpy. Should you make any more the process should be smoother.

**Pull request merged**
