### PR TITLE
Add secure standalone client and server example

### PR DESCRIPTION
**Pull request by mbruns42**
Signed-off-by: Melanie Bruns <mbruns42@mail.uni-paderborn.de>

### CODE REVIEW

**Comment by kevinherron** [comment]
Now that I've moved the standalone examples to their own module the README needs to explain how the server can generate a keystore as well... 

Are you set on using openssl for the example or should we modify one or both to use the `SelfSignedCertificateBuilder`?

**Comment by mbruns42** [comment]
I modified the server to use the SelfSignedCertificateBuilder and mentioned explicitely in the README that there are two options and which part of the code demonstrates what.

**Comment by mbruns42** [comment]
@kevinherron Do you have any more remarks?

**Comment by kevinherron** [comment]
No, sorry, I just lost of track of this 👍  Thanks for the reminder.

**Pull request merged**
