### PR TITLE
fix #144: add a CONTRIBUTING.md file

### LINKED ISSUE #144: Add a CONTRIBUTING.md file
I think it is necessary to add a file about contributing to Milo, also see #143 

Most Eclipse projects have this and I think the one from Eclipse Hono [1] could act as a base for Milo as well.

@kevinherron If you like I can create such a file for Milo

[1] https://github.com/eclipse/hono/blob/master/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by kevinherron** [comment]
Can you check whatever box that lets me push tweaks to this PR?

**Comment by ctron** [comment]
"Allow edits from maintainers. " ... that is checked.

**Comment by kevinherron** [comment]
Hmm. I don't know why I can't push to it.

```
kevin@kevins-mbp ~/D/milo> git remote -v
ctron   https://github.com/ctron/milo.git (fetch)
ctron   https://github.com/ctron/milo.git (push)
origin  https://github.com/eclipse/milo.git (fetch)
origin  https://github.com/eclipse/milo.git (push)

kevin@kevins-mbp ~/D/milo> git push ctron
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 520 bytes | 520.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/ctron/milo.git
 ! [remote rejected] ctron/feature/add_contributing_file_1 -> ctron/feature/add_contributing_file_1 (permission denied)
error: failed to push some refs to 'https://github.com/ctron/milo.git'
```

**Comment by kevinherron** [comment]
Can you apply this patch?

[Tweaks_to_CONTRIBUTING_md.patch.txt](https://github.com/eclipse/milo/files/1446439/Tweaks_to_CONTRIBUTING_md.patch.txt)

**Comment by ctron** [comment]
Looks like that worked.

**Comment by kevinherron** [comment]
Thanks dude! 👍

**Pull request merged**
