### PR TITLE
First cut for JavaDoc

### PR DESCRIPTION
**Pull request by Enomine88**

### CODE REVIEW

**Comment by kevinherron** [comment]
Unfortunately adding Javadocs to any of the built-in structures or enums is not going to work - these structures are occasionally re-generated by a code generator that isn't public and any Javadocs would be lost.

**Comment by Enomine88** [comment]
So everyone who wants to use Milo with feature that have no examples in the internet has to copy each classname and search it in the OPC UA Specification? I don't think that is a good idea... Can we find an other solution? My brother says an open source project, which has no documentation is not able to be used. And this is what i think, too, as i try to use Milo since 6 weeks and have not much idea what to do ;)

Classes to use main function of Milo have to be explained in Code, so a developer can understand WHILE PROGRAMMING, without looking into specification 4 hours a day.

Thanks - Enomine

**Comment by kevinherron** [comment]
I fully expect *anybody* who uses this library to have a copy of the spec for reference. I have no intention of trying to reproduce the contents of the spec inside Javadocs.

I agree that there should be documentation where possible, and many of the interfaces you are exposed to as a user of the library have docs, but right now javadocs on any auto-generated code isn't a possibility.

**Comment by pturmel** [comment]
I would suggest that your brother has limited exposure to open source. 
The vast majority is way short on documentation.  Not that it shouldn't 
be made better, but a fan of open source needs to have more realistic 
expectations.  Contributors are often volunteers -- you can't *make* 
them write documentation.

Lots of programmers work from specs, by the way.  That's what specs are 
for, after all.

On 5/21/19 8:41 AM, Enomine88 wrote:
[trim /]

> My brother says an open source project, which has no 
> documentation is not able to be used.

**Comment by Enomine88** [comment]
Excuse me please, english is not my native language. False interpretations of my sentences may occur.

I didn't want to force somebody to make javadoc. I wanted to start for it by myself =)

Thanks - Enomine

**Comment by Enomine88** [comment]
Okay
HistoryReadDetails and ReadRawModifiedDetails does not have Javadoc and its not possible because of generating these files from code-generator.

But QualifiedName has Javadoc.

How to see which class can have a Javadoc and which not? Can you provide a list of packages that are "allowed" to have javadoc and a list of those, that may not?

Thanks - Enomine

**Comment by Enomine88** [comment]
Well you said "no ... reproduce the contents of the spec inside Javadocs". In QualifiedName.java is already contents of the spec inside. See Part 3 chapter 8.3.
How did it come there? Was it auto-generated or copied by hand?

Thanks - Enomine

**Comment by kevinherron** [comment]
QualifiedName is not generated.

These packages and classes are:
```
**/Ua*Loader*,
**/org/eclipse/milo/opcua/stack/core/types/structured/*,
**/org/eclipse/milo/opcua/stack/core/types/enumerated/*,
**/org/eclipse/milo/opcua/sdk/core/CefactEngineeringUnits.java,
**/org/eclipse/milo/opcua/sdk/client/model/nodes/objects/*,
**/org/eclipse/milo/opcua/sdk/client/model/nodes/variables/*,
**/org/eclipse/milo/opcua/sdk/client/model/types/objects/*,
**/org/eclipse/milo/opcua/sdk/client/model/types/variables/*,
**/org/eclipse/milo/opcua/sdk/server/model/methods/*,
**/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/*,
**/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/*,
**/org/eclipse/milo/opcua/sdk/server/model/types/objects/*,
**/org/eclipse/milo/opcua/sdk/server/model/types/variables/*,
**/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/*,
**/org/eclipse/milo/opcua/stack/core/Identifiers.java,
**/org/eclipse/milo/opcua/stack/core/StatusCodes.java,
**/org/eclipse/milo/opcua/stack/core/types/TypeInitializer.java,
**/org/opcfoundation/opcua/binaryschema/*
```

**Pull request closed without merging**
