### PR TITLE
Opcua aml

### PR DESCRIPTION
**Pull request by kdorofeev**
Initial implementation of AML to OPCUA information model conversion following the [companion spec](https://opcfoundation.org/developer-tools/specifications-unified-architecture/opc-unified-architecture-for-automationml/)

### CODE REVIEW

**Comment by ctron** [comment]
Hi @kdorofeev you will need to sign the Eclipse Contributor Agreement – https://www.eclipse.org/legal/ecafaq.php

In addition you will need to add the Signed-Off footer in the git commit with the e-mail you registered the ECA with.

Let me know if you need any help.

**Comment by kdorofeev** [comment]
hi @ctron weird.. just checked the commit metadata 
```
"commit": {
    "author": {
      "name": "kdorofeev",
      "email": "dorofeev@fortiss.org",
      "date": "2017-05-12T09:12:12Z"
    },
    "committer": {
      "name": "kdorofeev",
      "email": "dorofeev@fortiss.org",
      "date": "2017-05-12T09:12:12Z"
    },
    "message": "fix ip-validation check\n\nSigned-off-by: kdorofeev <dorofeev@fortiss.org>"


```
everything's looking ok from my point of view. I got CLA signed using this email. Any idea on this? Thanks!

**Comment by ctron** [comment]
I just check using the Eclipse CLA lookup tool. You are right!

But it looks like not all commits in this PR are signed off, could that be?

**Comment by kdorofeev** [comment]
@ctron thanks! forgot to update the initial one

**Comment by kevinherron** [comment]
I need to look into this a little closer, but at first glance this doesn't look like something we'll be able to merge.

It looks like it's built around the idea that the NodeSet file(s) from the OPC foundation for this companion spec are present and because of whatever stupid legal reason we aren't allowed to have those files as part of the Milo project. They aren't even allowed to be part of the repository.

**Comment by kdorofeev** [comment]
ouch.. I'll have a look if I can get rid of those files easily. Actually they create only a static part of the address space, which is same for each aml file. It should be possible to create those parts manually, not using OPC Foundation xml's.

**Comment by kevinherron** [comment]
Don't spend too much time on it. If I understand what this is, then I've already written a generic version of this using JAXB to generate code from the official schemas. It can load *any* of the information models, it's not tied to one of them. 

I wasn't planning on making it part of Milo for the same reasons, but I can try to get it into a clean enough state for an initial source dump this week.

**Comment by kevinherron** [comment]
I've open-sourced some of my initial work:

https://github.com/digitalpetri/uanodeset-parser
https://github.com/digitalpetri/information-models

I'm available on the gitter.im channel if you have questions.

**Pull request closed without merging**
